add more fine connection checks

diff --git a/nova-scheduler-ra b/nova-scheduler-ra
--- a/nova-scheduler-ra
+++ b/nova-scheduler-ra
@@ -37,14 +37,16 @@ OCF_RESKEY_config_default="/etc/nova/nova.conf"
 OCF_RESKEY_user_default="nova"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
 OCF_RESKEY_monitor_binary_default="netstat"
-OCF_RESKEY_server_queue_port_default="5672"
+OCF_RESKEY_database_server_port_default="3306"
+OCF_RESKEY_amqp_server_port_default="5672"
 
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
 : ${OCF_RESKEY_monitor_binary=${OCF_RESKEY_monitor_binary_default}}
-: ${OCF_RESKEY_server_queue_port=${OCF_RESKEY_server_queue_port_default}}
+: ${OCF_RESKEY_database_server_port=${OCF_RESKEY_database_server_port_default}}
+: ${OCF_RESKEY_amqp_server_port=${OCF_RESKEY_amqp_server_port_default}}
 
 #######################################################################
 
@@ -111,12 +113,20 @@ The pid file to use for this OpenStack SchedulerService (nova-scheduler) instanc
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>
 
-<parameter name="server_queue_port" unique="0" required="0">                                                                                                                                                              
+<parameter name="database_server_port" unique="0" required="0">                                                                                                                                                              
+<longdesc lang="en">                                                                                                                                                                                                      
+The listening port number of the database server. Mandatory to perform a monitor check                                                                                                                                        
+</longdesc>                                                                                                                                                                                                               
+<shortdesc lang="en">Database listening port</shortdesc>                                                                                                                                                                      
+<content type="integer" default="${OCF_RESKEY_database_server_port_default}" />                                                                                                                                              
+</parameter>  
+
+<parameter name="amqp_server_port" unique="0" required="0">                                                                                                                                                              
 <longdesc lang="en">                                                                                                                                                                                                      
 The listening port number of the AMQP server. Mandatory to perform a monitor check                                                                                                                                        
 </longdesc>                                                                                                                                                                                                               
 <shortdesc lang="en">AMQP listening port</shortdesc>                                                                                                                                                                      
-<content type="integer" default="${OCF_RESKEY_server_queue_port_default}" />                                                                                                                                              
+<content type="integer" default="${OCF_RESKEY_amqp_server_port_default}" />                                                                                                                                              
 </parameter>      
 
 <parameter name="additional_parameters" unique="0" required="0">
@@ -204,16 +214,18 @@ nova_scheduler_monitor() {
 
     # Check whether we are supposed to monitor by logging into nova-scheduler
     # and do it if that's the case.
-    if ! check_binary $OCF_RESKEY_monitor_binary; then 
-		ocf_log warn "$OCF_RESKEY_monitor_binary missing, can not monitor!" 
-	else
-		PID=`cat $OCF_RESKEY_pid`
-		# check the connection according to the PID
-		AMQP_CO_CHECK=`"$OCF_RESKEY_monitor_binary" -punt | egrep "$OCF_RESKEY_server_queue_port$PID" | egrep -q "ESTABLISHED"`
-    fi
-    rc=$?
-    if [ $rc -ne 0 ]; then
-        ocf_log err "Nova Scheduler is not connected to the queue message service: $rc"
+    if ! check_binary $OCF_RESKEY_monitor_binary; then
+                ocf_log warn "$OCF_RESKEY_monitor_binary missing, can not monitor!"
+        else
+                PID=`cat $OCF_RESKEY_pid`
+                # check the connection according to the PID
+                SCHEDULER_AMQP_CO_CHECK=`"$OCF_RESKEY_monitor_binary" -punt | egrep "$OCF_RESKEY_database_server_port" | egrep "$PID" | egrep -q "ESTABLISHED"`
+                rc_amqp=$?
+                SCHEDULER_DATABASE_CO_CHECK=`"$OCF_RESKEY_monitor_binary" -punt | egrep "$OCF_RESKEY_amqp_server_port" | egrep "$PID" | egrep -q "ESTABLISHED"`
+                rc_database=$?
+        fi
+    if [ $rc_amqp -ne 0 ] || [ $rc_database -ne 0 ]; then
+        ocf_log err "Nova Scheduler is not connected to the AMQP server and/or the database server: $rc"
         return $OCF_NOT_RUNNING
     fi
 
