indentation block

diff --git a/nova-scheduler-ra b/nova-scheduler-ra
--- a/nova-scheduler-ra
+++ b/nova-scheduler-ra
@@ -227,29 +227,29 @@ nova_scheduler_monitor() {
     # Check whether we are supposed to monitor by logging into nova-scheduler
     # and do it if that's the case.
     if ! check_binary $OCF_RESKEY_monitor_binary; then
-                ocf_log warn "$OCF_RESKEY_monitor_binary missing, can not monitor!"
-        else
-			if [ $OCF_RESKEY_zeromq = true ]; then
-				PID=`cat $OCF_RESKEY_pid`
-				SCHEDULER_DATABASE_CO_CHECK=`"$OCF_RESKEY_monitor_binary" -punt | grep "$OCF_RESKEY_database_server_port" | grep "$PID" | grep -q "ESTABLISHED"`
-				rc_database=$?
-				if [ $rc_database -ne 0 ]; then
-				    ocf_log err "Nova Scheduler is not connected to the database server: $rc_database"
-				    return $OCF_NOT_RUNNING
-				fi
-			else
-                PID=`cat $OCF_RESKEY_pid`
-                # check the connections according to the PID
-                SCHEDULER_DATABASE_CO_CHECK=`"$OCF_RESKEY_monitor_binary" -punt | grep "$OCF_RESKEY_database_server_port" | erep "$PID" | grep -q "ESTABLISHED"`
-                rc_database=$?
-                SCHEDULER_AMQP_CO_CHECK=`"$OCF_RESKEY_monitor_binary" -punt | grep "$OCF_RESKEY_amqp_server_port" | grep "$PID" | grep -q "ESTABLISHED"`
-                rc_amqp=$?
-				if [ $rc_amqp -ne 0 ] || [ $rc_database -ne 0 ]; then
-				    ocf_log err "Nova Scheduler is not connected to the AMQP server and/or the database server: AMQP connection test returned $rc_amqp and database connection test returned $rc_api""
-				    return $OCF_NOT_RUNNING
-				fi
-			fi
-        fi
+        ocf_log warn "$OCF_RESKEY_monitor_binary missing, can not monitor!"
+    else
+	    if [ $OCF_RESKEY_zeromq = true ]; then
+		    PID=`cat $OCF_RESKEY_pid`
+		    SCHEDULER_DATABASE_CO_CHECK=`"$OCF_RESKEY_monitor_binary" -punt | grep "$OCF_RESKEY_database_server_port" | grep "$PID" | grep -q "ESTABLISHED"`
+		    rc_database=$?
+		    if [ $rc_database -ne 0 ]; then
+		        ocf_log err "Nova Scheduler is not connected to the database server: $rc_database"
+		        return $OCF_NOT_RUNNING
+		    fi
+	    else
+            PID=`cat $OCF_RESKEY_pid`
+            # check the connections according to the PID
+            SCHEDULER_DATABASE_CO_CHECK=`"$OCF_RESKEY_monitor_binary" -punt | grep "$OCF_RESKEY_database_server_port" | egrep "$PID" | grep -q "ESTABLISHED"`
+            rc_database=$?
+            SCHEDULER_AMQP_CO_CHECK=`"$OCF_RESKEY_monitor_binary" -punt | grep "$OCF_RESKEY_amqp_server_port" | grep "$PID" | grep -q "ESTABLISHED"`
+            rc_amqp=$?
+		    if [ $rc_amqp -ne 0 ] || [ $rc_database -ne 0 ]; then
+	            ocf_log err "Nova Scheduler is not connected to the AMQP server and/or the database server: AMQP connection test returned $rc_amqp and database connection test returned $rc_api"
+		        return $OCF_NOT_RUNNING
+		    fi
+	    fi
+    fi
 
     ocf_log debug "OpenStack NovaScheduler (nova-scheduler) monitor succeeded"
     return $OCF_SUCCESS
